@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindGroupCommandParser" as FindGroupCommandParser LOGIC_COLOR
participant "d:FindGroupCommand" as FindGroupCommand LOGIC_COLOR
participant "newGroup:Group" as Group LOGIC_COLOR
participant "r:CommandResult" as CommandResultSuccess LOGIC_COLOR
participant "r:CommandResult" as CommandResultFail LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find_group g/T03")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("find_group g/T03")
activate AddressBookParser

create FindGroupCommandParser
AddressBookParser -> FindGroupCommandParser
activate FindGroupCommandParser

FindGroupCommandParser --> AddressBookParser
deactivate FindGroupCommandParser

AddressBookParser -> FindGroupCommandParser : parse("g/T03")
activate FindGroupCommandParser

create FindGroupCommand
FindGroupCommandParser -> FindGroupCommand
activate FindGroupCommand

FindGroupCommand --> FindGroupCommandParser :
deactivate FindGroupCommand

FindGroupCommandParser --> AddressBookParser : d
deactivate FindGroupCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindGroupCommandParser -[hidden]-> AddressBookParser
destroy FindGroupCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> FindGroupCommand : execute(m)
activate FindGroupCommand

alt Group exists in Model
FindGroupCommand -> Model : updateFilteredPersonList(predicate))
activate Model

Model --> FindGroupCommand
deactivate Model

create CommandResultSuccess
FindGroupCommand -> CommandResultSuccess
activate CommandResultSuccess
CommandResultSuccess --> FindGroupCommand
deactivate CommandResultSuccess

else Group does not exist in Model

create CommandResultFail
FindGroupCommand -> CommandResultFail
activate CommandResultFail

CommandResultFail --> FindGroupCommand
deactivate CommandResultFail

FindGroupCommand --> LogicManager : r
deactivate FindGroupCommand
end

[<--LogicManager
deactivate LogicManager
@enduml
